package com.delai.bees.tops.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
* Created by Mybatis Generator on 2019/03/24
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class BitSignalConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Id
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Key
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Address
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Position
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Val
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Integer val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Enable
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Remark
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Create_Time
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bit_Signal_Config.Last_Update_Time
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Date lastUpdateTime;

    private com.delai.bees.tops.document.SignalConfig signal;

    public void setSignal(com.delai.bees.tops.document.SignalConfig signal) {
        this.signal = signal;
    }

    public com.delai.bees.tops.document.SignalConfig getSignal() {
        return this.signal;
    }
}