package com.delai.bees.tops.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
* Created by Mybatis Generator on 2019/03/24
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class LineProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Id
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.On
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Date on;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Off
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Date off;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.OEE
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String oee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.EFF
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String eff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Products
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long products;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Rejected
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long rejected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Loss
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long loss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Time
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Stacker_Product
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long stackerProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Bottle_Blowing_Product
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long bottleBlowingProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Line_Product.Implanter_Product
     *
     * @mbg.generated Sun Mar 24 11:42:48 CST 2019
     */
    private Long implanterProduct;
}